### ISSUE TITLE
problem of "new_dev.dict"

### ISSUE THREAD

**Issue by njcx-ai** [wangbo9719/StAR_KGC#1]
for the script "get_new_dev_dict.py", it need "new_dev.dict" in "evaluate", however,  only WN18RR already have  "new_dev.dict".

**Comment by njcx-ai** [comment]
![image](https://user-images.githubusercontent.com/60687114/120344372-1bf5c100-c32c-11eb-8863-3dce5d15f682.png)

**Comment by wangbo9719** [comment]
You can run the first two commands in README to get "new_dev.dict" for FB15k-237. 
The first command with "--do_train" is used to train a basic model to select the top candidates in the evaluation phase.
Then the second one with "--do_eval" aims to generate the new development set. 
Note, this is a two-stage process, please do not use "--do_train" and "--do_eval" at the same time.

**Comment by wangbo9719** [comment]
Close this issue due to no reply.
