### ISSUE TITLE
OSError: [WinError 6] 句柄无效。

### ISSUE THREAD

**Issue by NoviceCrom** [wangbo9719/StAR_KGC#10]
During executing section 4.1, i got the following exception. Any solutions? 
![QQ截图20220406115029](https://user-images.githubusercontent.com/48437212/161893464-9e08f0e4-0b60-415a-a7d6-7a14d0595025.jpg)

**Comment by wangbo9719** [comment]
Thanks for your interest in StAR. 

StAR hasn't be tested a lot on Windows. And I'm sorry that I have no idea about the solution. 
Maybe you could check the similar solutions for this ERROR in Github.
