### ISSUE TITLE
About negative sampling

### ISSUE THREAD

**Issue by LSX-Sneakerprogrammer** [wangbo9719/StAR_KGC#11]
Hi, I am a little confused with the negative sampling process. I saw in the paper, you have mentioned that the wrong triples are generated by replacing either the head or tail entity with another entity randomly sampled. But in the negetive_sampling function in kb_dataset.py, it has the probability to generate wrong triples through corrupting the relation. So, may I ask if there is a difference between these two methods? Hope you could help me with this problem, thanks a lot!

**Comment by LSX-Sneakerprogrammer** [comment]
I just found the default is the same as describing in the paper. Sorry for bothering lol

**Comment by wangbo9719** [comment]
Thanks for your attention to our work. 
If you have any other questions, please feel free to ask~
