### ISSUE TITLE
DATASET

### ISSUE THREAD

**Issue by qiushuigongchang** [wangbo9719/StAR_KGC#13]
hi, I'm a little confused  ,why to reformat original NELL-One as the three benchmarks above

**Comment by wangbo9719** [comment]
Thanks for your attention.
This work was done two years ago. I can not remember the details clearly. 
My impression is that the main purpose of reformatting is to obtain the natural language text of entities and relations.

**Comment by qiushuigongchang** [comment]
Thanks a lot
