### ISSUE TITLE
Inquiry about Experimental Setup and Runtime

### ISSUE THREAD

**Issue by yw3l** [wangbo9719/StAR_KGC#19]
Dear @wangbo9719 
First of all, thank you for sharing your excellent work on StAR_KGC. I am particularly interested in reproducing the results presented in this paper. To ensure that I accurately replicate the experiments, I would like to ask for some details regarding the experimental setup:
**Hardware Configuration**: Could you please share the details of the hardware configuration used for running the experiments? Specifically, information on the GPU, would be very helpful.
**Runtime**: I would also appreciate it if you could give an estimate of the time it took to run the main experiments. This will help me plan my experiments more effectively.
Best regards,
yw3l

**Comment by wangbo9719** [comment]
Thanks for your attention to our work. 

 I use an RTX 3090 GPU to conduct all experiments. 

Based on the 3090, the running time of main experiments on WN18RR and FB15k-237 are around 9h and 2 days respectively. 
I forgot the specific training time. You can run the listed commands to preview the time predicted by 'tqdm' as approximate time.

**Comment by yw3l** [comment]
@wangbo9719 thank u ! you really helped me!
