### ISSUE TITLE
new_dev.dict of fb15k-237

### ISSUE THREAD

**Issue by gyf6666** [wangbo9719/StAR_KGC#20]
Hello, I need a lot of time in the process of obtaining new _ dev.dict of fb15k-237 data set. Note that there is new _ dev.dict of wn18rr data set in your file, but there is no new _ dev.dict of fb15k-237 data set. Can you provide it  This will save me a lot of time.

**Comment by wangbo9719** [comment]
Sorry, I have lost the data.
