### ISSUE TITLE
The role of mixed float?

### ISSUE THREAD

**Issue by yhjiujiu** [wangbo9719/StAR_KGC#4]
hi, Thanks for your sharing of this paper, i have a question about the 2.1 step which are the mixed float computation package, its function whether to speed ​​up training ?  and  the second question is "KGE/StAR_KGC/StAR/transformers/configuration_utils.py", line 182, in from_pretrained
   raise EnvironmentError(msg)
OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert/config.json' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: /root/.cache/torch/transformers/5c6eb663edfa884554ead90bd31a56bd13c655097d981a6a7a4f3fc67d17fdf6."
i cannot find the file according its prompt, how to solve this problem? Hope for your reply. thanks!!

**Comment by wangbo9719** [comment]
Thanks for your attention. 

For your first question, the package is used to speed up training. If you don't install it, just remove _"--fp16"_ in commands. 

As for the second question, what value did you use for _--model_name_or_path_? 
According to your error log 'https://s3.amazonaws.com/models.huggingface.co/bert/bert/config.json', it seems like you use _bert_ rather than _bert-base-uncased_ or other trained bert models.

**Comment by yhjiujiu** [comment]
Thanks for your answer. I solved the second question by modified the value of --model_name_or_path. I want to use the mixed float computation, but got the problem when installed the last package. 
![image](https://user-images.githubusercontent.com/39623606/134930744-cfa3be73-90ca-4e9f-91e0-efc6fa07b429.png)

**Comment by wangbo9719** [comment]
Sorry, it is difficult for me to find out the cause of this error with just one picture and I have not encountered this error before.
This package is related to the cuda environment. 
Maybe you can find the reason in its official repo: https://github.com/NVIDIA/apex.

**Comment by yhjiujiu** [comment]
Thanks for your passionate reply.

**Comment by yhjiujiu** [comment]
Sorry, Can you confirm that the last pip statement is executed under apex/apex folder?  or apex/?
