### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by Jiang-X-Pro** [wangbo9719/StAR_KGC#5]
thanks for your excellent work in KGC filed.
i have not seen the code yet and i am confused about the input . the input text of entity is the short version like  "Gary Rydstrom" or  the long version like "Gary Roger Rydstrom is an American sound designer and director. He has won seven Academy Awards for his work in sound for movies."?

**Comment by wangbo9719** [comment]
Thanks for your attention.

We use the long one as input.

**Comment by Jiang-X-Pro** [comment]
Thanks for your response , and could you explain the  why we need the steps of "do_train" and "do_eval" for getting a new dev subset? I am not clear with the get_new_dev_dict.py about how it works.Hope for your reply!!!

**Comment by wangbo9719** [comment]
The original dev set is the same size as the test set. If we use the original dev set in the validation stage, it will take about one hour (sorry, I forgot the accurate time) for one validation. And there will be many validations during the training stage, which is very time-consuming.
Therefore, we develop a new dev subset to mitigate this problem. We apply a basic model to get the ranked top-50 candidate entities that are hard to predict for this triple. And the other candidates far from the gold entity are ignored. The selected entity set of each triple replaces the original candidate entity set containing all entities in the graph. In this way, we speed up the validation stage and maintain its effectiveness.

**Comment by Jiang-X-Pro** [comment]
thanks for your quick reply , do you mean that for the fact (h,r,{t1,t2,...,tn})  , you keep the top-50 t_i which gets the lower score than other entity t_j by Bert(h,r,t_i) < Bert(h,r,t_j) ?

**Comment by wangbo9719** [comment]
Sorry, I forgot that the Bert(h,r,t_i) is lower or higher than Bert(h,r,t_j) in the implement. Whatever, Bert(h,r,t_i) is closer than Bert(h,r,t_j) and the "closer " means that the t_i is more likely to be mispredicted by the trained model as a gold entity than other t_j.

**Comment by Jiang-X-Pro** [comment]
Thanks for your reply!
Could you tell me how much memory you use for the evaluation of fb15-237. I use up it with 50GB.

**Comment by wangbo9719** [comment]
Sorry, I forgot the detail. But I used a 24G GPU before, which is enough.

**Comment by Jiang-X-Pro** [comment]
Thanks for your great work.
Could you tell me how to use the new dev file "new_dev.dict"?

**Comment by wangbo9719** [comment]
Add "--do_eval" to the training command of StAR. For example, section 4.1 in README.

**Comment by Jiang-X-Pro** [comment]
according to the code https://github.com/wangbo9719/StAR_KGC/blob/890dd544059e79d7e9ac0e79c1ac30d94c291ad6/StAR/kbc/kb_dataset.py#L91, it will use the dev.tsv instead,should I rename the file "new_dev.dict" as "dev.tsv"?

**Comment by wangbo9719** [comment]
It has been written directly in https://github.com/wangbo9719/StAR_KGC/blob/890dd544059e79d7e9ac0e79c1ac30d94c291ad6/StAR/link_prediction/train.py#L625.

**Comment by Jiang-X-Pro** [comment]
it went wrong when reproducing the  results of NELL,  usepacka was not found

**Comment by wangbo9719** [comment]
Sorry for the wrong command. You can just remove the 'usepacka' parameter. It may be a copy mistake in the readme.md writing. I will revise it.
