### ISSUE TITLE
The program runs very slowly

### ISSUE THREAD

**Issue by q248953144** [wangbo9719/StAR_KGC#6]
hello,I run this program  ./StAR/run_get_unsemble_data.py  very slowly. 
![image](https://user-images.githubusercontent.com/33486182/144342775-3bc4215a-1369-45ec-b641-3857bff143ca.png)

**Comment by wangbo9719** [comment]
This is my running time. 
![image](https://user-images.githubusercontent.com/48275080/144346027-8e48ffc9-ae75-4bdf-8176-dcfb66a58a4f.png)
And I use an RTX 3090 GPU.
