### ISSUE TITLE
how to generate the prediction result in detail?

### ISSUE THREAD

**Issue by tideng777** [wangbo9719/StAR_KGC#7]
Hi guys, good work. I wanna to check hit@10 results in detail. I mean how to generate the candicates result for test.tsv? Which file show the result of prediction candicates in detail, not just metrices? Thanks a lot. 

![image](https://user-images.githubusercontent.com/57006809/147352491-fc12704a-1abb-4c2c-8e07-96bbadb8e815.png)

**Comment by wangbo9719** [comment]
Sorry, there is no direct file about the ranking results. You can alter the predict() function in train.py to get the results yourself.
